eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
    bk1:
      connection-timeout: 20000
      driver-class-name: org.postgresql.Driver
      idle-timeout: 59000
      jdbc-url: jdbc:postgresql://42.193.39.39:35432/mic_author?currentSchema=author
      max-lifetime: 60000
      maximum-pool-size: 15
      minimum-idle: 3
      password: tjkj2022!><@
      pool-name: HikariPool-bk1
      username: postgres
    pri:
      connection-timeout: 20000
      driver-class-name: org.postgresql.Driver
      idle-timeout: 59000
      jdbc-url: jdbc:postgresql://42.193.39.39:35432/mic_author?currentSchema=author
      max-lifetime: 60000
      maximum-pool-size: 15
      minimum-idle: 3
      password: tjkj2022!><@
      pool-name: HikariPool-pri
      username: postgres
  redis:
    database: 3
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    port: 36379
    timeout: 5000
wf:
  weburl: http://127.0.0.1:9007/

server:
  host: https://eureka.china315net.com

dict:
  pid:
    comp_type: 4 #公司类别
    business_type: 7 #业务类别
    prod_type: 10 #产品类型
    prod_proper_datatype: 16 #产品属性数据类型
  prod_proper_datatype:
    text: 17
    number: 18
    boolean: 19